### ISSUE TITLE
SDL error - Passed a NULL mutex

### ISSUE THREAD

**Issue by xBrendonx** [SoundChaser83/devilutionx-apocrypha#10]
![sdl](https://user-images.githubusercontent.com/114590448/211665672-bc57848c-3a24-46e7-8a3f-2fbef27474f5.png)

**Important information**
Apocrypha version: 0.4.2, 0.5.0, 0.5.1 (possibly any version) (not built, i just downloaded the releases)

**Describe**
The game suddenly started to show this error, whenever i open it with Win10; i never did anything, sometimes i get this error, sometimes the game runs just fine, it seems to be random; sometimes if i wait and try later, the game could run without any error. On Win7, it works normally.

**To Reproduce**
I don't think it's easy to reproduce it, since it seems to be random.

**Additional context**
- I don't have an active antivirus;
- Tried disabling firewall, or anything that could cause some problems with the game;
- Tried to recreate the folder in the path shown in the error, used the Source code (zip) to recreate the "devilutionX" folder. At first it seemed to fix the problem, but the error still keeps popping out randomly.

**Comment by SoundChaser83** [comment]
I'm going to show this to the people in the DevilutionX Discord and see what they have to say about it. Thanks for your report!

**Comment by SoundChaser83** [comment]
Okay I just pushed a [new release](https://github.com/SoundChaser83/devilutionx-apocrypha/releases/tag/v0.5.2) which hopefully fixes the problem. Feel free to let me know if the problem still occurs!

**Comment by xBrendonx** [comment]
Ok so, first time i didn't get the error but now i do. I think it's because of my pc... The error is the same

**Comment by SoundChaser83** [comment]
That's strange...and I'm very sorry this is happening! Out of curiosity, have you tried playing DevilutionX (what this mod is built from) and do you get a similar error there too?

**Comment by xBrendonx** [comment]
Late response, but Apocrypha worked fine for 3 days until now; i'm getting the same error but NOT with DevilutionX, which is working fine with win10

**Comment by SoundChaser83** [comment]
A couple questions for you...1) When does the error happen? Right at launch? Sometime while in a game? If so, are you in single player or multi player? 2) Are you playing in Hellfire mode? (This is highly recommended as there are currently multiple parts of the code that only work with that mode on.) 3) What language are you playing the game in? (I think there's some possibility that the error messages are all in English which is why I ask. I know DevX has had some issues in different languages before.)

**Comment by xBrendonx** [comment]
The error happens right at launch, if i click OK it just keeps appearing and doesn't let me play; i'm in single player, playing with Hellfire; i'm playing in english.

**Comment by SoundChaser83** [comment]
I got some feedback from the DevilutionX Discord that I should try removing dthread, so I've done that and pushed a [new release](https://github.com/SoundChaser83/devilutionx-apocrypha/releases/download/v0.5.3/apocrypha_windows_x64.zip) that hopefully addresses the crash once and for all. Let me know what happens!

**Comment by xBrendonx** [comment]
Ok so, i tested it for a few days and the error never happened. Thank you so much for fixing it! I'm closing this issue, if it'll ever happen again i'll open another one.
Again, thanks. It really was annoying.

**Comment by SoundChaser83** [comment]
That's fantastic! I'm glad it finally seems to have been worked out.

**Comment by xBrendonx** [comment]
Ehm... I hate to say it, but the error happened again :/ still in beta 0.5.3, although it happened after a longer time than before, if that matters. The error is the same.
(wth devilutionX it's working as usual)

**Comment by SoundChaser83** [comment]
Ugh...I'm so sorry about this. =( I'll run it by the Discord again and see if anyone has any further ideas on how to fix it.

**Comment by SoundChaser83** [comment]
Okay, try the [newest release](https://github.com/SoundChaser83/devilutionx-apocrypha/releases/download/v0.5.4/apocrypha_windows_x64.zip) now. I've been told by the Discord that this should eliminate all remaining instances of locking functions that I still had which DevX has already gotten rid of by now.

**Comment by xBrendonx** [comment]
Hi, the problem is still there :S i made a [video](https://user-images.githubusercontent.com/114590448/216790380-8ede4424-f190-4eac-9a05-66d85f5198be.mov) that shows what exactly happens though.
Again, this is periodic. Most of the time it works, but there could be an entire day where no matter what i do, it just won't start... on windows10, that is.

**Comment by SoundChaser83** [comment]
Wow...I really thought I'd solved it this time but I guess not. I'm going to really have to dig into the code to figure out what's going on. I really appreciate all of your feedback though so that I know when there's a problem, especially since I can't seem to really test this issue on my own system.

**Comment by xBrendonx** [comment]
Really? This makes me think if there's something wrong with my OS, i don't think since i never had any compatibility issues with other programs or something like that, but i'm no expert on this matter.

**Comment by SoundChaser83** [comment]
I wouldn't blame your OS, I figure there must be something wrong with the game that's been patched out of DevilutionX but I still have since I'm basing the mod off of DevX 1.3. I'm no expert here either though, and I've mainly been trying to get help from some of the main DevX contributors, so I'll have to ask them again.

**Comment by AJenbo** [comment]
@xBrendonx have you tried downloading the latest SDL2.dll from https://www.libsdl.org/ and seeing if replacing the one that came with the game fixes the issue?

or maybe just the one that is included with devilutionx

**Comment by SoundChaser83** [comment]
I've also released a [new version](https://github.com/SoundChaser83/devilutionx-apocrypha/releases/tag/v0.6.1) which you should try out, and make sure to replace all of the files as mentioned in the release notes.

If that still doesn't work, perhaps try re-installing Diablo and Hellfire or re-download them from GOG so you can get new .mpq files. There may be some possibility that your .mpq files are corrupted and they need to be replaced with fresh ones.

**Comment by AJenbo** [comment]
Or if you like do an MD5 sum of your MPQ files and we can validate them

**Comment by xBrendonx** [comment]
Thanks to both. I redownloaded the mpq files, now using beta 0.6.1 and it seems to work. I'll let you know if the error persists.

**Comment by xBrendonx** [comment]
Didn't have this problem anymore for a month straight, so i guess it's fixed now. Thank you.

**Comment by SoundChaser83** [comment]
Amazing! I'm so glad things have been working properly now! As always, feel free to post again if the problem comes back or you find another bug somewhere else in the game.
